Update pytest.yml

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -28,7 +28,6 @@ jobs:
               - "pyproject.toml"
               - "codecov.yml"
               
-
   test-core:
     needs: check-paths
 
@@ -41,23 +40,19 @@ jobs:
     name: test-core (${{ matrix.os }}, ${{ matrix.python-version }})
     runs-on: ${{ matrix.os }}
     steps:
-      - if: ${{ needs.check-paths.outputs.should_run == 'true' }}
-        uses: actions/checkout@v6
+      - uses: actions/checkout@v6
 
-      - if: ${{ needs.check-paths.outputs.should_run == 'true' }}
-        uses: astral-sh/setup-uv@v8.1.0
+      - uses: astral-sh/setup-uv@v8.1.0
         with:
           version: "0.11.16"
           python-version: ${{ matrix.python-version }}
 
       - name: Update the environment and test with python ${{ matrix.python-version }}
-        if: ${{ needs.check-paths.outputs.should_run == 'true' }}
         run: |
           uv sync --locked --group dev
           uv run --frozen pytest --cov=pystatpower --cov-report=xml
 
       - name: Upload coverage to Codecov
-        if: ${{ needs.check-paths.outputs.should_run == 'true' }}
         uses: codecov/codecov-action@v6
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
@@ -87,26 +82,54 @@ jobs:
     name: test-minimum-scipy (${{ matrix.os }}, ${{ matrix.deps.python-version }}, scipy == ${{ matrix.deps.scipy-version }})
     runs-on: ${{ matrix.os }}
     steps:
-      - if: ${{ needs.check-paths.outputs.should_run == 'true' }}
-        uses: actions/checkout@v6
+      - uses: actions/checkout@v6
 
-      - if: ${{ needs.check-paths.outputs.should_run == 'true' }}
-        uses: astral-sh/setup-uv@v8.1.0
+      - uses: astral-sh/setup-uv@v8.1.0
         with:
           version: "0.11.16"
           python-version: ${{ matrix.deps.python-version }}
 
       - name: Update the environment and test with python ${{ matrix.deps.python-version }}
-        if: ${{ needs.check-paths.outputs.should_run == 'true' }}
         run: |
           uv sync --locked --group dev
           uv pip install scipy==${{ matrix.deps.scipy-version }} --no-build
           uv run --frozen pytest --cov=pystatpower --cov-report=xml
 
       - name: Upload coverage to Codecov
-        if: ${{ needs.check-paths.outputs.should_run == 'true' }}
         uses: codecov/codecov-action@v6
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           files: ./coverage.xml
           flags: test-minimum-scipy-${{ matrix.os }}-py${{ matrix.deps.python-version }}-scipy${{ matrix.deps.scipy-version }}
+
+  check-pytest-status:
+    needs: [check-paths, test-core, test-minimum-scipy]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check Jobs Status
+        run: |
+          CHECK_PATH_RESULT="${{ needs.check-paths.result }}"
+          PYTEST_CORE_RESULT="${{ needs.test-core.result }}"
+          PYTEST_MINIMUM_SCIPY_RESULT="${{ needs.test-minimum-scipy.result }}"
+
+          echo "check-paths status: ${CHECK_PATH_RESULT}"
+          echo "test-core status: ${PYTEST_CORE_RESULT}"
+          echo "test-minimum-scipy: ${PYTEST_MINIMUM_SCIPY_RESULT}"
+
+          if [ "$CHECK_PATH_RESULT" = "failure" ] || [ "$CHECK_PATH_RESULT" = "cancelled" ]; then
+            echo "❌ Path check failed or cancelled."
+            exit 1
+          fi
+
+          if [ "$PYTEST_CORE_RESULT" = "failure" ] || [ "$PYTEST_CORE_RESULT" = "cancelled" ]; then
+            echo "❌ PyTest core test failed or cancelled."
+            exit 1
+          fi
+
+          if [ "$PYTEST_MINIMUM_SCIPY_RESULT" = "failure" ] || [ "$PYTEST_MINIMUM_SCIPY_RESULT" = "cancelled" ]; then
+            echo "❌ PyTest minimum SciPy test failed or cancelled."
+            exit 1
+          fi
+
+          echo "✅ All tests passed or gracefully skipped!"
